- type: job
  id: SeniorDoctor
  name: Ведущий врач
  description: Обучайте новичков медицине и химии!
  playTimeTracker: JobSeniorDoctor
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs
  startingGear: SeniorDoctorGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: SeniorDoctorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSeniorPhysician
    back: ClothingBackpackMedicalFilled
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    head: ClothingHeadHatBeretSeniorPhysician
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
