- type: playTimeTracker
  id: JobCentralCommandOperator

- type: playTimeTracker
  id: JobCentralCommandSecGavna

- type: playTimeTracker
  id: JobCentralCommandSecOfficer

- type: playTimeTracker
  id: JobCentralCommandCargo

- type: playTimeTracker
  id: JobCentralCommandAssistant

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: BPLATech

- type: playTimeTracker
  id: BPLAMED

- type: playTimeTracker
  id: JobCentralCommandAdmiral

- type: playTimeTracker
  id: JobDeliveryman

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobFugitive

- type: playTimeTracker
  id: JobStudent

- type: playTimeTracker
  id: JobExplorer

- type: playTimeTracker
  id: JobFreelancerGear

- type: playTimeTracker
  id: JobSAI
