- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 14400 #4 hrs
  - !type:DepartmentTimeRequirement
    department: Security
    time: 21600 #6 hrs # Corvax-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurityFilledDetective
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    outerClothing: ClothingOuterVestDetective
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurityFilledDetective
  duffelbag: ClothingBackpackDuffelSecurityFilledDetective
