- type: startingGear
  id: ADTERTSecurityGearEVA_L
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlue
    back: ADTClothingBackpackERTSecurityFilledL
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskBreath
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitStorage: OxygenTankFilled
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCommand
    belt: ADTClothingBeltMilitaryWebbingRPSSL
    pocket1:
