[game]
hostname = "🛰️ Corvax — Атара 🌌 [TTS]"
desc = "Корвакс — первый русскоязычный проект в Space Station 14.\nНа этом сервере средние требования к RP.\n[Имеется интеграция TTS (Text-To-Speech)]"
map_pool = "CorvaxDefaultMapPool"
maxplayers = 150
soft_max_players = 70
map_rotation = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
