[game]
hostname = "🛰️ Corvax — Атара 🌌⚡[TTS][NEXT]"
desc = "[Требуется 15 часов на другом сервере Corvax!]\nКорвакс — первый русскоязычный проект в Space Station 14.\n⚡ На этом сервере используется сборка Corvax Next. Больше контента, возможностей и взаимодействия!\nНа этом сервере средние требования к RP.\nИмеется интеграция TTS (Text-To-Speech)"
maxplayers = 150
soft_max_players = 75
map_rotation = true

[server]
lobby_name = "🛰️ Corvax — Атара 🌌⚡"

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 900
custom_reason = "Для доступа на этот сервер вам необходимо отыграть на другом сервере Corvax как минимум 15 часов."

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
