[game]
hostname = "🛰️ Corvax — Атара 🌌"
desc = "Корвакс первый русскоязычный проект в Space Station 14.\nНа этом сервере средние требования к RP.\n[Имеется интеграция TTS (Text-To-Speech)]"
map_pool = "CorvaxMapPool"
maxplayers = 150
soft_max_players = 70
map_rotation = false

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 30

[rules]
time = 10.0

[queue]
enabled = true

[tts]
enabled = true

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
