[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
discord = "https://discord.ss14.ru"
github = "https://github.com/space-syndicate/space-station-14"
wiki = "https://station14.ru"
patreon = "https://boosty.to/corvax"
appeal = "https://discord.ss14.ru"
bug_report = "https://github.com/space-syndicate/space-station-14/issues/new/choose"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game]
lobbyduration = 360
map_pool = "CorvaxMapPool"
secret_weight_prototype = "CorvaxSecretDefault"

[server]
rules_file = "CorvaxRuleset"

[discord]
rich_main_icon_id = "corvax"

[admin]
see_own_notes = true
