[net]
tickrate = 30

[infolinks]
discord = "https://discord.gg/tZgNv2wJuJ"
github = "https://github.com/SpaceStories/space-station-14"
wiki = "https://spacestories.club"
patreon = "https://boosty.to/spacestories14"
appeal = "https://discord.gg/tZgNv2wJuJ"

[viewport]
maximum_width = 26
