[game]
hostname = "🛰️ Corvax — Эхо ☄️ [TTS]"
desc = "[Требуется 10 часов на другом сервере Corvax!]\nКорвакс — первый русскоязычный проект в Space Station 14.\nНа этом сервере средние требования к RP.\nИмеется интеграция TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 160
soft_max_players = 70
map_rotation = true

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_hours = 10
custom_reason = "Для доступа на этот сервер вам необходимо отыграть на другом сервере Corvax как минимум 10 часов."

[rules]
time = 10.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
