[server]
rules_file = "RulesCorvax.txt"

[game]
fallbackpreset = "extended"
lobbyenabled = true
role_timers = true
artifact_round_end_timer = 0.0

[ic]
flavor_text = true
punctuation = false

[ooc]
enable_during_round = false

[atmos]
space_wind = true
space_wind_max_velocity = 22.0

[shuttle]
emergency_early_launch_allowed = true
arrivals_map = "/Maps/Misc/corvax_terminal.yml"

[vote]
restart_required_ratio = 0.85
same_type_timeout = 300.0
timerrestart = 30
map_enabled = true
preset_enabled = false
