[game]
hostname = "🛰️ Corvax — Нова 🪐[TTS]"
desc = "[Требуется 40 часов на другом сервере Corvax!]\nКорвакс — первый русскоязычный проект в Space Station 14.\nНа этом сервере высокие требования к RP.\nИмеется интеграция TTS (Text-To-Speech)."
maxplayers = 120
soft_max_players = 60
map_rotation = false

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 2400
custom_reason = "Для доступа на этот сервер вам необходимо отыграть на другом сервере Corvax как минимум 40 часов."

[rules]
time = 10.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
