[game]
hostname = "🛰️ Corvax — Солярис 🌕"
desc = "Корвакс первый русскоязычный проект в Space Station 14.\nНа Солярисе средние требования к RP.\nИмеется интеграция TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 160
soft_max_players = 80
map_rotation = true

[rules]
time = 180.0

[queue]
enabled = true

[tts]
enabled = true

[discord_auth]
enabled = true

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
