[game]
hostname = "🛰️ Corvax — Солярис 🌕 [TTS]"
desc = "Корвакс — первый русскоязычный проект в Space Station 14.\nНа этом сервере средние требования к RP.\nИмеется интеграция TTS (Text-To-Speech)."
map_pool = "CorvaxDefaultMapPool"
maxplayers = 160
soft_max_players = 80
map_rotation = true

[rules]
time = 10.0

[hub]
advertise = true
tags = "lang:ru,rp:med,region:eu_e,tts"
