- type: entity
  id: CrateChaplainClothing
  parent: CrateGenericSteel
  name: ящик с богослужебной одеждой
  description: Ящик, содержащий одежду для богослужения и распространения веры.
  components:
    - type: StorageFill
      contents:
      - id: ClothingUniformJumpsuitChaplain
        amount: 2
      - id: ClothingUniformJumpskirtChaplain
        amount: 2
      - id: ClothingShoesColorBlack
        amount: 2
      - id: ClothingUniformJumpsuitMonasticRobeDark
      - id: ClothingUniformJumpsuitMonasticRobeLight
      - id: ClothingNeckStoleChaplain
      - id: ClothingOuterHoodieChaplain
      - id: ClothingHeadHatHoodNunHood
      - id: ClothingOuterNunRobe
      - id: ClothingHeadHatFez
      - id: ClothingHeadHatPlaguedoctor
      - id: ClothingHeadHatWitch
      - id: ClothingHeadHatWitch1
      - id: ClothingOuterPlagueSuit
      - id: ClothingMaskPlague
