- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 6h
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 6h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 60h
  weight: 9
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering

- type: chameleonOutfit
  id: SeniorEngineerChameleonOutfit
  job: SeniorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
