- type: job
  id: Virusolog
  name: job-name-virusolog
  playTimeTracker: JobVirusolog
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600
  startingGear: VirusologGear
  icon: "Virologist"
  supervisors: job-supervisors-cmo
  canBeAntag: false
  access:
    - Medical
    - Chemistry
    - Maintenance

- type: startingGear
  id: VirusologGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackVirology
    shoes: ClothingShoesColorWhite
    id: VirusologPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedical
    # the purple glasses?
  innerclothingskirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled

- type: entity
  parent: BasePDA
  id: VirusologPDA
  name: Virusolog PDA
  description: Shiny and sterile. Has a built-in health analyzer.
  components:
    - type: PDA
      id: VirusologIDCard
      state: pda-medical
    - type: Icon
      state: pda-medical
    - type: HealthAnalyzer
      scanDelay: 1.2
      scanningEndSound:
        path: "/Audio/Items/Medical/healthscanner.ogg"
    - type: CrewMonitoringConsole

- type: entity
  parent: IDCardStandard
  id: VirusologIDCard
  name: virusolog ID card
  components:
    - type: Sprite
      layers:
        - state: default
        - state: idmedicaldoctor
    - type: PresetIdCard
      job: Virusolog
