- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    #start-_CorvaxNext: surgery
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 1.5
    #end-_CorvaxNext: surgery
    - type: Skills # Corvax-Next-Skills
      skills:
      - ShuttleControl
      - Shooting
      - AdvancedBuilding
      - Surgery
      - MedicalEquipment
      - Butchering

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol
