- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000
  icon: "Lawyer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Brig
  - Maintenance


- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlue  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    right hand: BriefcaseBrownFilled
  innerclothingskirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
