- type: job
  id: RbFighter
  name: royal battle fighter
  description: Kill other pretenders for the medal!
  playTimeTracker: JobRbFighter
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: You don't have something as a boss.
