- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 #15 hrs
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: SurgeonGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltSurgicalBoardFilled
    shoes: ClothingShoesColorWhite
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesNitrile
