- type: job
  id: StarDustOfficer
  name: job-name-star-dust-officer
  description: job-description-star-dust-officer
  playTimeTracker: JobStarDustOfficer
  requirements:
  - !type:RoleTimeRequirement
    role: JobWarden
    time: 18000 #10 hrs
  startingGear: StarDustOfficerGear
  icon: "JobIconStarDustOfficer"
  supervisors: job-supervisors-star-dust-officer
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Detective
  - Command
  - Service
  extendedAccess:
  - Armory
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddHoloSpecial
    holo: MobHoloparasiteGuardian
  # HoloparasiteInjector

- type: startingGear
  id: StarDustOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitStarDustOfficer
    back: ClothingBackpackSecurityFilled
    head: ClothingHeadHatBeretHoS
    eyes: ClothingEyesGlassesSecurity
    shoes: ClothingShoesBootsCombatFilled
    id: SecurityPDA
    ears: ClothingHeadsetAltSecurity
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolG22NonLethal
    outerClothing: ClothingOuterVestArmorSec
  innerClothingSkirt: ClothingUniformJumpsuitStarDustOfficer
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
