- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 #5 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
