- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 54000 #15 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    head: ClothingHeadHatBeretRND
    jumpsuit: ClothingUniformJumpsuitSeniorResearcher
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
  innerclothingskirt: ClothingUniformJumpskirtSeniorResearcher
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
