- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleApi
  name: API Role
  components:
  - type: MindRole
    antagPrototype: Api
    roleType: soloAntagonist
  - type: ApiRole
  - type: ThiefBeaconAccess

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVoxRaiders
  name: Vox Raider Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    exclusiveAntag: true
    antagPrototype: VoxRaiders
  - type: VoxRaidersRole

- type: entity
  parent: MindRoleVoxRaiders
  id: MindRoleVoxRaidersCommander
  name: Vox Raiders Commander Role
  components:
  - type: MindRole
    antagPrototype: VoxRaidersCommander
