- type: job
  id: BKCCCargo
  name: job-name-centcomcargo
  description: job-description-centcomcargo
  playTimeTracker: JobCentralCommandCargo
  setPreference: true
  startingGear: CCCargo
  icon: JobIconNanotrasen
  supervisors: job-supervisors-hoh
  canBeAntag: false
  weight: 1
  requireAdminNotify: true
  joinNotifyCrew: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 63000
    - !type:RoleTimeRequirement
      role: JobCentralCommandAssistant
      time: 10800
    - !type:DepartmentTimeRequirement
      department: CentCom
      time: 21600
  access:
    - CCGeneral
    - CCCargo
  accessGroups:
    - AllAccess
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]

- type: startingGear
  id: CCCargo
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: CCCargoPDA
    ears: ClothingHeadsetCentCom
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: entity
  parent: OrdenPDA
  id: CCCargoPDA
  name: Centcom Cargo PDA
  description: Light green sign of walking bureaucracy.
  components:
    - type: Pda
      id: IDCardCentComCargoBackmen
      state: pda-centcomcargo
      penSlot:
        startingItem: PenCentcom
        whitelist:
          tags:
            - Write
    - type: PdaBorderColor
      borderColor: "#00842e"
    - type: Icon
      sprite: Debiloid1984/Objects/Devices/pda.rsi
      state: pda-centcomcargo

- type: entity
  parent: CentcomIDCardDeathsquad
  id: IDCardCentComCargoBackmen
  name: Id карта ЦК Грузчика
  components:
    - type: Sprite
      layers:
        - state: silver
        - state: idiaa
        - state: idcargotechnician
    - type: Item
      heldPrefix: silver
    - type: PresetIdCard
      job: BKCCCargo
    - type: Access
      tags:
        - CCCargo
        - CCGeneral
      groups:
        - AllAccess
