name: Close PRs on master

on:
  pull_request_target:
    types: [ opened, ready_for_review ]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{(github.head_ref == 'master' || github.head_ref == 'main' || github.head_ref == 'develop' || github.head_ref == 'stable' || github.head_ref == 'staging')
        && github.event.pull_request.head.repo.fork}}

    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Спасибо за ваш вклад! Похоже, вы создали запрос на удаление из основной ветки или другой основной ветки разработки. Это [то, чего вам следует избегать] (https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/), и, таким образом, этот запрос на удаление был автоматически закрыт. \n \n Мы рекомендуем вам следовать [нашему использованию git documentation](https://docs.spacestation14.com/en/general-development/setup/git-for-the-ss14-developer.html). \n \n Вы можете перенести свою текущую работу в другую ветку, выполнив [эти команды](https://ohshitgit.com/#accidental-commit-master). Затем вы можете повторно создать свой запрос на извлечение, используя новую ветку."

    # If you prefer to just comment on the pr and not close it, uncomment the below and comment the above

    # - uses: actions/github-script@v7
    #   with:
    #     script: |
    #       github.rest.issues.createComment({
    #         issue_number: ${{ github.event.number }},
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: "Thank you for your contribution! It appears you created a pull request from the master branch or another main development branch. This is [something you should avoid doing](https://jmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)\n\nYou can move your current work to another branch by following [these commands](https://ohshitgit.com/#accidental-commit-master). Then, you may recreate your pull request using the new branch. \n\n This pull request won't be automatically closed. However, a maintainer may close it for this reason."})
